server {
    listen 80;             # Nginx escuta na porta 80

    location / {
        proxy_pass http://api:8000;    # repassa para o serviço 'api' na rede Compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}